server:
  port: 9090

spring:
  application:
    # 服务名
    name: spring-cloud-gateway
  cloud:
    nacos:
      discovery:
        register-enabled: false
        server-addr: localhost:8848


    gateway:
      discovery:
        locator:
          # 可以使用服务名的方式访问，例如
          #   http://localhost:9090/alibaba-consumer/all/user?origin=abc
          #   http://localhost:9090/alibaba-provider/user
          enabled: true
